// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/collaborator.ts";
import * as $2 from "./routes/calculator.tsx";
import * as $3 from "./routes/contact.tsx";
import * as $4 from "./routes/gallery.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/inspired.tsx";
import * as $$0 from "./islands/FlowerCount.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/collaborator.ts": $1,
    "./routes/calculator.tsx": $2,
    "./routes/contact.tsx": $3,
    "./routes/gallery.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/inspired.tsx": $6,
  },
  islands: {
    "./islands/FlowerCount.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
